export interface GeneratedDesign {
  readonly title: string
  readonly html: string
}

function escapeHtml(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')
}

function titleFromPrompt(prompt: string): string {
  const words = prompt.trim().replace(/[^\p{L}\p{N}\s-]/gu, '').split(/\s+/).slice(0, 5)
  const title = words.join(' ')
  return title ? title[0].toUpperCase() + title.slice(1) : 'Untitled design'
}

export function generateMockDesign(prompt: string, previousHtml?: string): GeneratedDesign {
  const title = titleFromPrompt(prompt)
  const escapedPrompt = escapeHtml(prompt)
  const iteration = previousHtml ? 'Refined direction' : 'First direction'

  return {
    title,
    html: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
</head>
<body class="min-h-screen bg-stone-950 text-stone-100 antialiased">
  <main class="mx-auto flex min-h-screen max-w-6xl flex-col justify-center px-8 py-16">
    <p class="mb-5 text-sm font-semibold uppercase tracking-widest text-lime-300">${iteration}</p>
    <h1 class="max-w-4xl text-5xl font-semibold tracking-tight sm:text-7xl">${escapeHtml(title)}</h1>
    <p class="mt-7 max-w-2xl text-lg leading-8 text-stone-300">${escapedPrompt}</p>
    <div class="mt-12 grid gap-4 md:grid-cols-3">
      <section class="border border-stone-800 bg-stone-900 p-6"><strong class="text-2xl">01</strong><p class="mt-8 text-stone-400">Clear structure</p></section>
      <section class="border border-stone-800 bg-lime-300 p-6 text-stone-950"><strong class="text-2xl">02</strong><p class="mt-8 text-stone-700">Purposeful contrast</p></section>
      <section class="border border-stone-800 bg-stone-900 p-6"><strong class="text-2xl">03</strong><p class="mt-8 text-stone-400">Responsive by default</p></section>
    </div>
    <details class="mt-10 max-w-2xl border-t border-stone-800 pt-5">
      <summary class="cursor-pointer font-medium text-lime-300">Explore the design intent</summary>
      <p class="mt-4 leading-7 text-stone-400">This offline-ready prototype was generated by OmniDesign's development provider.</p>
    </details>
  </main>
</body>
</html>`,
  }
}
