// Regenerates src/electron/workspace/alpineRuntime.ts from the installed alpinejs package so the
// Alpine runtime can be injected into compiled designs locally (no external CDN). Run: pnpm vendor:alpine
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const source = readFileSync(require.resolve('alpinejs/dist/cdn.min.js'))
const version = require('alpinejs/package.json').version
const here = path.dirname(fileURLToPath(import.meta.url))
const destination = path.resolve(here, '../src/electron/workspace/alpineRuntime.ts')

const contents = `// AUTO-GENERATED by scripts/vendor-alpine.mjs — do not edit by hand.
// Vendored Alpine.js v${version} runtime (base64 of alpinejs/dist/cdn.min.js). It is injected inline
// into compiled designs so Alpine works locally, without loading anything from an external CDN.
export const alpineRuntimeVersion = '${version}'
export const alpineRuntimeBase64 =
  '${source.toString('base64')}'
`

writeFileSync(destination, contents, 'utf8')
console.log(`Vendored Alpine v${version} (${source.length} bytes) -> ${destination}`)
