// Regenerates src/electron/workspace/alpineRuntime.ts from the installed alpinejs package (plus the
// bundled plugins) so the Alpine runtime can be injected into compiled designs locally (no external
// CDN). Run: pnpm vendor:alpine
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
// Plugins must come BEFORE core Alpine: each registers an `alpine:init` listener, and core may start
// synchronously when its deferred script executes, so the listeners must already be in place.
const collapse = readFileSync(require.resolve('@alpinejs/collapse/dist/cdn.min.js'))
const core = readFileSync(require.resolve('alpinejs/dist/cdn.min.js'))
const source = Buffer.concat([collapse, Buffer.from('\n'), core])
const version = require('alpinejs/package.json').version
const collapseVersion = require('@alpinejs/collapse/package.json').version
const here = path.dirname(fileURLToPath(import.meta.url))
const destination = path.resolve(here, '../src/electron/workspace/alpineRuntime.ts')

const contents = `// AUTO-GENERATED by scripts/vendor-alpine.mjs — do not edit by hand.
// Vendored Alpine.js v${version} runtime with the @alpinejs/collapse v${collapseVersion} plugin
// (base64 of the concatenated cdn.min.js builds, collapse first). Injected inline into compiled
// designs so Alpine and x-collapse work locally, without loading anything from an external CDN.
export const alpineRuntimeVersion = '${version}'
export const alpineRuntimeBase64 =
  '${source.toString('base64')}'
`

writeFileSync(destination, contents, 'utf8')
console.log(`Vendored Alpine v${version} + collapse v${collapseVersion} (${source.length} bytes) -> ${destination}`)
